### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [AndreasHagman/MMM-NOKElectricityForecast#1]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with a screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by KristjanESPERANTO** [comment]
@AndreasHagman Did you noticed this? :slightly_smiling_face:

**Comment by AndreasHagman** [comment]
Hey, thank you so much. I will add this as soon a possible!

fre. 18. okt. 2024, 01:41 skrev Kristjan ESPERANTO ***@***.***

**Comment by AndreasHagman** [comment]
Should be published now @KristjanESPERANTO  :D

**Comment by KristjanESPERANTO** [comment]
Nice. Now your module looks better (with a screenshot) in the new list :slightly_smiling_face:
